
export const GET_DATA_EARNING = 'GET_DATA_EARNING';
export const GET_DATA_EARNING_SUCCESS = 'GET_DATA_EARNING_SUCCESS';
export const GET_DATA_EARNING_ERROR = 'GET_DATA_EARNING_ERROR';
export const RESET_DATA_EARNING = 'RESET_DATA_EARNING';

export const GET_DATA_TRANSACTIONS_HISTORY = 'GET_DATA_TRANSACTIONS_HISTORY';
export const GET_DATA_TRANSACTIONS_HISTORY_SUCCESS = 'GET_DATA_TRANSACTIONS_HISTORY_SUCCESS';
export const GET_DATA_TRANSACTIONS_HISTORY_ERROR = 'GET_DATA_TRANSACTIONS_HISTORY_ERROR';
export const RESET_DATA_TRANSACTIONS_HISTORY = 'RESET_DATA_TRANSACTIONS_HISTORY';
export const COUNT_VERIFY_ACCOUNT_NUMBER = 'COUNT_VERIFY_ACCOUNT_NUMBER'
export const SET_HEADER_TITLE = 'SET_HEADER_TITLE'
export const SET_NATIVE_NAVIGATION = 'SET_NATIVE_NAVIGATION'
export const SET_NATIVE_NAVIGATION_BACK = 'SET_NATIVE_NAVIGATION_BACK'

export const SET_PAGE_DATA = 'SET_PAGE_DATA'

